#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
#CONFIG_NCS_SAMPLES_DEFAULTS=y

CONFIG_ASSERT=y
CONFIG_ASSERT_VERBOSE=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_DEBUG_THREAD_INFO=y

CONFIG_LOG_PRINTK=n
CONFIG_DEBUG_INFO=y

CONFIG_EXTRA_EXCEPTION_INFO=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

# General configuration
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_NVS_LOOKUP_CACHE=y
CONFIG_SETTINGS_NVS_NAME_CACHE=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_NVS_LOG_LEVEL_WRN=y

CONFIG_HWINFO=y
CONFIG_DK_LIBRARY=y
CONFIG_PM_SINGLE_IMAGE=y
CONFIG_PM_PARTITION_SIZE_SETTINGS_STORAGE=0x8000
CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE=n

#UART2 towards nRF52840
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NRF_SW_LPUART=y
CONFIG_NRF_SW_LPUART_INT_DRIVEN=y
CONFIG_UART_2_ASYNC=y
CONFIG_UART_2_INTERRUPT_DRIVEN=n
CONFIG_UART_2_NRF_HW_ASYNC=y
CONFIG_UART_2_NRF_HW_ASYNC_TIMER=2

CONFIG_NRF_SW_LPUART_MAX_PACKET_SIZE=255
CONFIG_NRF_SW_LPUART_INT_DRV_TX_BUF_SIZE=255

# Bluetooth configuration
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="Broadcaster"

CONFIG_BT_H4=y
CONFIG_BT_HCI=y

CONFIG_BT_WAIT_NOP=y

CONFIG_BT_L2CAP_TX_BUF_COUNT=8
CONFIG_BT_L2CAP_TX_MTU=33

CONFIG_BT_OBSERVER=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_SETTINGS=y
CONFIG_BT_RX_STACK_SIZE=2700

CONFIG_BT_BUF_EVT_RX_SIZE=255
CONFIG_BT_BUF_EVT_RX_COUNT=10
CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=58
CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT=20
CONFIG_BT_BUF_CMD_TX_SIZE=255

CONFIG_BT_EXT_ADV=y
CONFIG_BT_EXT_ADV_MAX_ADV_SET=5

CONFIG_BT_BUF_ACL_TX_SIZE=37
CONFIG_BT_BUF_ACL_RX_SIZE=37


CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
#CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_DATA_LEN_UPDATE=n

CONFIG_BT_HOST_CCM=y

CONFIG_LOG=y

CONFIG_RESET_ON_FATAL_ERROR=n

CONFIG_INIT_STACKS=y

CONFIG_PM_DEVICE=y

CONFIG_SHELL=y
CONFIG_SHELL_WILDCARD=n
CONFIG_SHELL_PROMPT_UART="mosh:~$ "
CONFIG_SHELL_ARGC_MAX=40
# -h and --help options are handled in Modem Shell
CONFIG_SHELL_HELP_OPT_PARSE=n
# Command line buffer is set this large to enable writing of certificates and injecting A-GNSS data on command line.
CONFIG_SHELL_CMD_BUFF_SIZE=3584
# Shell stack has impact for modem shell application, not CONFIG_MAIN_STACK_SIZE
CONFIG_SHELL_STACK_SIZE=9216
# Shell RX buffer needs to be increased to avoid problems with test automation
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=512
CONFIG_SHELL_BACKEND_SERIAL_API_INTERRUPT_DRIVEN=y

CONFIG_DEBUG_THREAD_INFO=y

CONFIG_PM_PARTITION_SIZE_SETTINGS_STORAGE=0x2000

CONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU=y
